"""empty message

Revision ID: 624e7e15b711
Revises: b8c43b83d5f0
Create Date: 2020-07-23 20:09:58.587401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624e7e15b711'
down_revision = 'b8c43b83d5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('groupies', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'groupies')
    # ### end Alembic commands ###
